-- 1. Cleaned Headlines (Optimized for Analysis)
CREATE TABLE IF NOT EXISTS cleaned_headlines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    country TEXT NOT NULL,
    category TEXT,
    headline TEXT NOT NULL,
    ticker_tags TEXT[], -- Array of tickers
    regex_cleaned BOOLEAN DEFAULT FALSE,
    score_relevance FLOAT DEFAULT 0.0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_cleaned_headlines_date ON cleaned_headlines(date);
CREATE INDEX IF NOT EXISTS idx_cleaned_headlines_country ON cleaned_headlines(country);

-- 2. Market Factors (Factor-7 Output)
CREATE TABLE IF NOT EXISTS market_factors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL UNIQUE, -- One record per day
    rates JSONB, -- {state: "Spike", zscore: 2.5, trend: "Rising"}
    inflation JSONB,
    commodities JSONB,
    dollar JSONB,
    liquidity JSONB,
    risk JSONB,
    region JSONB,
    raw_changes JSONB, -- Store raw delta values for debugging
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_market_factors_date ON market_factors(date);

-- 3. Pattern RAG (Verified Success Patterns)
CREATE TABLE IF NOT EXISTS pattern_rag (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    sql_query TEXT NOT NULL,
    summary TEXT,
    example_events JSONB, -- List of dates/events that matched
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Meta RAG (Rules & Errors)
CREATE TABLE IF NOT EXISTS meta_rag (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    rule TEXT NOT NULL,
    error_type TEXT,
    evidence TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
