-- 1. Create yearly_summaries table if it doesn't exist
CREATE TABLE IF NOT EXISTS yearly_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year INTEGER NOT NULL,
    country TEXT NOT NULL DEFAULT 'US',
    summary TEXT,
    content JSONB, -- The full JSON report
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(year, country)
);

-- 2. Add content column to weekly_summaries if missing
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'weekly_summaries' AND column_name = 'content') THEN
        ALTER TABLE weekly_summaries ADD COLUMN content JSONB;
    END IF;
END $$;

-- 3. Add content column to monthly_summaries if missing
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'monthly_summaries' AND column_name = 'content') THEN
        ALTER TABLE monthly_summaries ADD COLUMN content JSONB;
    END IF;
END $$;

-- 4. Add content column to yearly_summaries if missing (redundant if just created, but safe)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'yearly_summaries' AND column_name = 'content') THEN
        ALTER TABLE yearly_summaries ADD COLUMN content JSONB;
    END IF;
END $$;
