-- 1. Global News Table (If not exists)
CREATE TABLE IF NOT EXISTS global_news_all (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    summary TEXT,
    published_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    country TEXT,
    signal_score FLOAT4 DEFAULT 0.0,
    source TEXT
);

-- 2. Weekly Summaries Table
CREATE TABLE IF NOT EXISTS weekly_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    country TEXT NOT NULL,
    summary TEXT,
    macro_tags JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_weekly_end_date ON weekly_summaries (end_date);
CREATE INDEX IF NOT EXISTS idx_weekly_country ON weekly_summaries (country);

-- 1.5 Daily Reports Table (Structured)
CREATE TABLE IF NOT EXISTS daily_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    country TEXT NOT NULL,
    content JSONB,
    summary TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_daily_date ON daily_reports (date);
CREATE INDEX IF NOT EXISTS idx_daily_country ON daily_reports (country);

-- 3. Monthly Summaries Table
CREATE TABLE IF NOT EXISTS monthly_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month DATE NOT NULL, -- YYYY-MM-01
    country TEXT NOT NULL,
    summary TEXT,
    macro_tags JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_monthly_month ON monthly_summaries (month);
CREATE INDEX IF NOT EXISTS idx_monthly_country ON monthly_summaries (country);

-- 4. Yearly Summaries Table
CREATE TABLE IF NOT EXISTS yearly_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year INT NOT NULL,
    country TEXT NOT NULL,
    summary TEXT,
    macro_tags JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_yearly_year ON yearly_summaries (year);
CREATE INDEX IF NOT EXISTS idx_yearly_country ON yearly_summaries (country);

-- 5. G9 Reports Table (Legacy/Alternative)
CREATE TABLE IF NOT EXISTS g9_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    type TEXT NOT NULL, -- 'WEEKLY' or 'MONTHLY'
    content TEXT NOT NULL,
    country TEXT DEFAULT 'US',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_reports_date_type ON g9_reports (date, type);
