import json
import os
import sys
from utils.supabase_client import run_sql

def setup_daily_report_table():
    print("🚀 Setting up G9 Daily Report Table...")

    create_daily_table = """
    CREATE TABLE IF NOT EXISTS daily_reports (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        date DATE NOT NULL,
        country TEXT NOT NULL,
        content JSONB, -- Structured JSON from DeepSeek
        summary TEXT, -- Plain text summary for easy reading
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
    SELECT 1;
    """
    idx_daily_1 = "CREATE INDEX IF NOT EXISTS idx_daily_date ON daily_reports (date); SELECT 1;"
    idx_daily_2 = "CREATE INDEX IF NOT EXISTS idx_daily_country ON daily_reports (country); SELECT 1;"
    
    print(f"Executing: CREATE TABLE daily_reports...")
    try:
        res = run_sql(create_daily_table)
        print(f"   Response: {res}")
        run_sql(idx_daily_1)
        run_sql(idx_daily_2)
        print("✅ Table 'daily_reports' created.")
    except Exception as e:
        print(f"❌ Failed to create daily_reports: {e}")

if __name__ == "__main__":
    setup_daily_report_table()
