import json
import os
import sys
from utils.supabase_client import run_sql

def setup_daily_report_table_v2():
    print("🚀 Setting up G9 Daily Report Table (v2)...")

    # Split into separate calls to avoid syntax errors
    sql1 = """
    CREATE TABLE IF NOT EXISTS daily_reports (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        date DATE NOT NULL,
        country TEXT NOT NULL,
        content JSONB,
        summary TEXT,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
    """
    
    sql2 = "CREATE INDEX IF NOT EXISTS idx_daily_date ON daily_reports (date);"
    sql3 = "CREATE INDEX IF NOT EXISTS idx_daily_country ON daily_reports (country);"
    
    print(f"Executing: CREATE TABLE daily_reports...")
    try:
        res = run_sql(sql1)
        print(f"   Response 1: {res}")
        res = run_sql(sql2)
        print(f"   Response 2: {res}")
        res = run_sql(sql3)
        print(f"   Response 3: {res}")
        print("✅ Table 'daily_reports' created.")
    except Exception as e:
        print(f"❌ Failed to create daily_reports: {e}")

if __name__ == "__main__":
    setup_daily_report_table_v2()
