import json
import os
import sys
from utils.supabase_client import run_sql

def setup_yearly_summary_table():
    print("🚀 Setting up G9 Yearly Summary Table...")

    # Yearly Summaries Table
    create_yearly_table = """
    CREATE TABLE IF NOT EXISTS yearly_summaries (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        year INT NOT NULL,
        country TEXT NOT NULL,
        summary TEXT,
        macro_tags JSONB,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
    SELECT 1;
    """
    idx_yearly_1 = "CREATE INDEX IF NOT EXISTS idx_yearly_year ON yearly_summaries (year); SELECT 1;"
    idx_yearly_2 = "CREATE INDEX IF NOT EXISTS idx_yearly_country ON yearly_summaries (country); SELECT 1;"
    
    print(f"Executing: CREATE TABLE yearly_summaries...")
    try:
        res = run_sql(create_yearly_table)
        print(f"   Response: {res}")
        run_sql(idx_yearly_1)
        run_sql(idx_yearly_2)
        print("✅ Table 'yearly_summaries' created.")
    except Exception as e:
        print(f"❌ Failed to create yearly_summaries: {e}")

if __name__ == "__main__":
    setup_yearly_summary_table()
