import json
import os
import sys
from utils.supabase_client import run_sql

def setup_summary_tables():
    print("🚀 Setting up G9 Summary Tables...")

    # Weekly Summaries Table
    create_weekly_table = """
    CREATE TABLE IF NOT EXISTS weekly_summaries (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        start_date DATE NOT NULL,
        end_date DATE NOT NULL,
        country TEXT NOT NULL,
        summary TEXT,
        macro_tags JSONB,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
    SELECT 1;
    """
    idx_weekly_1 = "CREATE INDEX IF NOT EXISTS idx_weekly_end_date ON weekly_summaries (end_date); SELECT 1;"
    idx_weekly_2 = "CREATE INDEX IF NOT EXISTS idx_weekly_country ON weekly_summaries (country); SELECT 1;"
    
    # Monthly Summaries Table
    create_monthly_table = """
    CREATE TABLE IF NOT EXISTS monthly_summaries (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        month DATE NOT NULL, -- YYYY-MM-01
        country TEXT NOT NULL,
        summary TEXT,
        macro_tags JSONB,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
    SELECT 1;
    """
    idx_monthly_1 = "CREATE INDEX IF NOT EXISTS idx_monthly_month ON monthly_summaries (month); SELECT 1;"
    idx_monthly_2 = "CREATE INDEX IF NOT EXISTS idx_monthly_country ON monthly_summaries (country); SELECT 1;"
    
    print(f"Executing: CREATE TABLE weekly_summaries...")
    try:
        res = run_sql(create_weekly_table)
        print(f"   Response: {res}")
        run_sql(idx_weekly_1)
        run_sql(idx_weekly_2)
        print("✅ Table 'weekly_summaries' created.")
    except Exception as e:
        print(f"❌ Failed to create weekly_summaries: {e}")

    print(f"Executing: CREATE TABLE monthly_summaries...")
    try:
        res = run_sql(create_monthly_table)
        print(f"   Response: {res}")
        run_sql(idx_monthly_1)
        run_sql(idx_monthly_2)
        print("✅ Table 'monthly_summaries' created.")
    except Exception as e:
        print(f"❌ Failed to create monthly_summaries: {e}")

if __name__ == "__main__":
    setup_summary_tables()
