import json
from utils.supabase_client import run_sql

def setup_database():
    print("🚀 Setting up Supabase Database...")

    # 1. Create Table
    create_table_sql = """
    CREATE TABLE IF NOT EXISTS global_news (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        summary TEXT,
        published_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        country TEXT,
        signal_score FLOAT4 DEFAULT 0.0,
        source TEXT
    );
    """
    print(f"Executing: CREATE TABLE global_news...")
    try:
        res = run_sql(create_table_sql)
        print("✅ Table created (or already exists).")
    except Exception as e:
        print(f"❌ Failed to create table: {e}")
        return

    # 2. Insert Sample Data
    # Check if data exists first to avoid duplicates (optional, but good practice)
    # For simplicity in this script, we'll just insert. 
    # In a real scenario, we might truncate or check count.
    
    sample_data_sql = """
    INSERT INTO global_news (title, summary, country, signal_score, published_at) VALUES
    ('Fed Signals Rate Cut', 'Jerome Powell hints at 25bps cut due to cooling inflation.', 'US', 0.9, NOW()),
    ('China Tech Rally', 'Alibaba and Tencent surge on new stimulus package announcement.', 'CN', 0.85, NOW()),
    ('Yen Weakens', 'BOJ maintains dovish stance despite inflation pressure.', 'JP', 0.7, NOW()),
    ('Samsung Electronics Earnings Shock', 'Chip demand slows down, impacting Q3 revenue.', 'KR', 0.88, NOW()),
    ('US Inflation Persistence', 'CPI data shows sticky inflation in services sector.', 'US', 0.75, NOW() - INTERVAL '1 day'),
    ('China Real Estate Crisis', 'Major developer defaults on bond payment.', 'CN', 0.82, NOW() - INTERVAL '2 days');
    """
    
    print(f"Executing: Inserting Sample Data...")
    try:
        res = run_sql(sample_data_sql)
        print("✅ Sample data inserted.")
    except Exception as e:
        print(f"❌ Failed to insert data: {e}")

if __name__ == "__main__":
    setup_database()
