import json
from utils.supabase_client import run_sql

def setup_reports_db():
    print("🚀 Setting up G9 Reports Database...")

    # Create Table
    create_table_sql = """
    CREATE TABLE IF NOT EXISTS g9_reports (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        date DATE NOT NULL,
        type TEXT NOT NULL, -- 'WEEKLY' or 'MONTHLY'
        content TEXT NOT NULL,
        country TEXT DEFAULT 'US',
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
    
    -- Create Index for fast retrieval
    CREATE INDEX IF NOT EXISTS idx_reports_date_type ON g9_reports (date, type);
    """
    
    print(f"Executing: CREATE TABLE g9_reports...")
    try:
        res = run_sql(create_table_sql)
        print("✅ Table 'g9_reports' created (or already exists).")
    except Exception as e:
        print(f"❌ Failed to create table: {e}")

if __name__ == "__main__":
    setup_reports_db()
