-- Recreate g9_intelligence_core with 3072 dimensions
DROP TABLE IF EXISTS g9_intelligence_core;

CREATE TABLE g9_intelligence_core (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_date DATE NOT NULL,
    ticker TEXT NOT NULL,
    sector TEXT,
    z_score FLOAT,
    macro_env JSONB,
    pattern_id TEXT,
    strategy_type TEXT, -- BUY, SELL, HOLD
    confidence_score FLOAT,
    final_logic TEXT,
    return_3d FLOAT,
    return_7d FLOAT,
    success_flag BOOLEAN,
    embedding VECTOR(3072), -- text-embedding-3-large
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Index for similarity search
CREATE INDEX ON g9_intelligence_core USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);
