-- Create news_archive table with same schema as ingest_news
create table if not exists news_archive (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text,
  clean_title text,
  url text unique,
  published_at timestamp with time zone,
  country text,
  source text,
  category text,
  importance_score double precision,
  summary text,
  is_refined boolean default false,
  title_ko text,
  summary_ko text,
  archived_at timestamp with time zone default timezone('utc'::text, now())
);

-- Optional: Create index on published_at for faster queries
create index if not exists idx_news_archive_published_at on news_archive (published_at);
