import os
import json
from datetime import datetime
from dotenv import load_dotenv
from supabase import create_client, Client

load_dotenv()

url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_KEY")

if not url or not key:
    print("Error: SUPABASE_URL or SUPABASE_KEY not found in .env")
    exit(1)

supabase: Client = create_client(url, key)

print(f"Connecting to {url}...")

# Mock Terminal Report
report_content = {
    "sections": [
        {
            "title": "MARKET_PULSE",
            "body": "REGIME: VOLATILE_EXPANSION\nCONFIDENCE: 82%\n\n> The algorithm detects a significant divergence in Vegas lines vs. Recent Form."
        },
        {
            "title": "ALPHA_OPPORTUNITIES",
            "items": [
                {"asset": "LAL vs PHX", "signal": "OVER 224.5", "reason": "Pace misalignment detected."},
                {"asset": "Steph Curry", "signal": "PTS > 28.5", "reason": "Regime Breakout imminent."}
            ]
        }
    ],
    "ascii_art": "  _  _  ____   __  \n | \| ||  _ \ /  \ \n | .` || |_) | /\ |\n |_|\_||____/ /__\|"
}

payload = {
    "date": datetime.utcnow().strftime("%Y-%m-%d"),
    "report_type": "TERMINAL_VIEW",
    "content": report_content,
    "metadata": {"source": "manual_seed_script"},
    "updated_at": datetime.utcnow().isoformat()
}

try:
    print("Attempting to insert report...")
    data, count = supabase.table("daily_reports").upsert(payload, on_conflict="date, report_type").execute()
    print("✅ Success! Mock Report Seeded.")
    print(data)
except Exception as e:
    print(f"❌ Failed to insert. Table 'daily_reports' likely missing.\nError: {e}")
    print("\nPLEASE RUN THIS SQL IN SUPABASE DASHBOARD:\n")
    print("""
    CREATE TABLE IF NOT EXISTS daily_reports (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        date DATE DEFAULT CURRENT_DATE,
        report_type TEXT NOT NULL, 
        content JSONB NOT NULL,    
        metadata JSONB,            
        created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
    );
    CREATE UNIQUE INDEX IF NOT EXISTS idx_reports_date_type ON daily_reports(date, report_type);
    """)
