"use client"

import { useState, useEffect, Suspense } from "react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { useSearchParams } from "next/navigation"
import {
    CloudSun, TrendingUp, Shield, DollarSign, Activity, Zap,
    ChevronRight, Info, CloudRain, CloudLightning, Sun, Moon, Terminal,
    ArrowUpRight, ArrowDownRight, Globe, Lock, Unlock, LogOut, RefreshCw
} from "lucide-react"
import { cn } from "@/lib/utils"
import { supabase } from "@/lib/supabase"

interface NewsItem {
    id: number
    title: string
    clean_title?: string
    published_at: string
    summary: string
    url?: string
    source?: string
    country?: string
    category?: string
    importance_score?: number
    short_summary?: string
    title_ko?: string
    summary_ko?: string
}

function getCountryFlag(country: string) {
    const map: Record<string, string> = {
        'US': '🇺🇸',
        'KR': '🇰🇷',
        'CN': '🇨🇳',
        'JP': '🇯🇵',
        'EU': '🇪🇺',
        'UK': '🇬🇧',
        'CRYPTO': '🪙',
        'ALL': '🌍'
    }
    return map[country] || '🌍'
}

function DashboardContent() {
    const router = useRouter()
    const searchParams = useSearchParams()
    const initialCountry = searchParams.get('country') || 'ALL'

    const [selectedFactor, setSelectedFactor] = useState<string | null>(null)
    const [selectedCountry, setSelectedCountry] = useState<string>(initialCountry)
    const [selectedCategory, setSelectedCategory] = useState<string>('ALL')
    const [selectedLanguage, setSelectedLanguage] = useState<string>('EN') // EN, KO
    const [news, setNews] = useState<NewsItem[]>([])
    const [loading, setLoading] = useState(true)
    const [currentDate, setCurrentDate] = useState<string>("")
    const [macroData, setMacroData] = useState<any>(null)
    const [theme, setTheme] = useState<'dark' | 'light'>('dark')

    const countries = ['ALL', 'US', 'KR', 'CN', 'JP']
    const comingSoonCountries = ['EU', 'CRYPTO']
    const categories = ['ALL', 'ECONOMY', 'POLITICS', 'SOCIETY', 'TECH']

    useEffect(() => {
        setCurrentDate(new Date().toLocaleDateString('en-US', {
            weekday: 'short',
            year: 'numeric',
            month: 'short',
            day: 'numeric'
        }))
    }, [])

    // Fetch Macro Data (Generated by GitHub Action)
    useEffect(() => {
        async function fetchMacroData() {
            try {
                const res = await fetch('/dashboard_data.json?t=' + new Date().getTime()) // Cache bust
                if (res.ok) {
                    const data = await res.json()
                    console.log("Macro Data Loaded:", data)
                    setMacroData(data)
                } else {
                    console.error("Failed to load macro data")
                }
            } catch (e) {
                console.error("Error loading macro data:", e)
            }
        }
        fetchMacroData()
    }, [])

    useEffect(() => {
        async function fetchData() {
            setLoading(true)
            console.log(`Fetching news for Country: ${selectedCountry}, Category: ${selectedCategory}`)

            const sevenDaysAgo = new Date()
            sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7)

            let query = supabase
                .from('ingest_news')
                .select('id, title, clean_title, published_at, summary, url, source, country, category, importance_score')

            // 1. Apply Filters FIRST
            query = query.gte('importance_score', 6)
                .gte('published_at', sevenDaysAgo.toISOString()) // FIX: Limit scan range

            if (selectedCountry !== 'ALL') {
                if (selectedCountry === 'CRYPTO') {
                    query = query.textSearch('title', "'bitcoin' | 'crypto' | 'btc' | 'eth'")
                } else {
                    query = query.eq('country', selectedCountry)
                }
            }

            if (selectedCategory !== 'ALL') {
                query = query.eq('category', selectedCategory)
            }

            // 2. Apply Sort & Limit LAST
            query = query.order('published_at', { ascending: false })
                .limit(50)

            const { data, error } = await query

            if (error) {
                console.error("Error fetching news:", error)
            }

            if (data) {
                console.log(`Fetched ${data.length} items`)
                setNews(data)
            }
            setLoading(false)
        }
        fetchData()

        // Real-time subscription
        const channel = supabase
            .channel('public:ingest_news')
            .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'ingest_news' }, (payload) => {
                console.log('New news:', payload)
                // In a real app, we'd prepend this to the list
            })
            .subscribe()

        return () => {
            supabase.removeChannel(channel)
        }
    }, [selectedCountry, selectedCategory])

    // Parse Macro Data or Use Fallback
    const weather = macroData?.weather || "Loading..."
    const weatherSummary = macroData?.weather_summary || "Analyzing market conditions..."
    const historian = macroData?.historian_insight || null

    // Macro Indicators (Dynamic from Factor Interpretation if available, else Mock)
    const macroIndicators = [
        { label: "RATES", value: macroData?.factor_interpretation?.rates || "Analyzing...", trend: "neutral", change: undefined, icon: Activity },
        { label: "DOLLAR", value: macroData?.factor_interpretation?.dollar || "Analyzing...", trend: "neutral", change: undefined, icon: DollarSign },
        { label: "RISK", value: macroData?.factor_interpretation?.risk || "Analyzing...", trend: "neutral", change: undefined, icon: CloudLightning },
        { label: "LIQUIDITY", value: macroData?.factor_interpretation?.liquidity || "Stable", trend: "neutral", change: undefined, icon: Unlock },
    ]

    // Regime Cards (Dynamic from Actions/Risks)
    const regimeCards = macroData?.actions ? macroData.actions.map((action: any, idx: number) => ({
        title: action.asset,
        status: action.type.toUpperCase(),
        vibe: action.label,
        color: action.type === 'buy' ? "text-emerald-400" : action.type === 'reduce' ? "text-rose-400" : "text-slate-400",
        border: action.type === 'buy' ? "border-emerald-500/30" : action.type === 'reduce' ? "border-rose-500/30" : "border-slate-500/30"
    })) : []

    const handleLogout = () => {
        // In a real app, you'd clear auth tokens here
        router.push('/')
    }

    const toggleTheme = () => {
        setTheme(prev => prev === 'dark' ? 'light' : 'dark')
    }

    const handleRefresh = () => {
        window.location.reload()
    }

    return (
        <div className={cn(
            "min-h-screen font-sans selection:bg-indigo-500/30 flex flex-col transition-colors duration-300 overflow-x-hidden",
            theme === 'dark' ? "bg-[#050505] text-slate-200" : "bg-slate-50 text-slate-900"
        )}>

            {/* LAYER 1: MACRO NOW BAR (Sticky Top) */}
            <div className={cn(
                "sticky top-0 z-50 backdrop-blur-md border-b shadow-lg transition-colors duration-300",
                theme === 'dark' ? "bg-[#0a0a0a]/95 border-white/5" : "bg-white/95 border-slate-200"
            )}>
                <div className="max-w-[1600px] mx-auto px-4 h-12 flex items-center justify-between overflow-x-auto no-scrollbar">
                    <div className="flex items-center gap-6 text-xs font-mono whitespace-nowrap">
                        <button
                            onClick={handleRefresh}
                            className="flex items-center gap-2 text-indigo-500 font-bold mr-4 hover:opacity-80 transition-opacity"
                            title="Refresh Dashboard"
                        >
                            <Activity size={14} />
                            <span>MACRO NOW</span>
                        </button>
                        {macroIndicators.map((item, idx) => (
                            <div key={idx} className={cn(
                                "flex items-center gap-2 border-r pr-6 last:border-0",
                                theme === 'dark' ? "border-white/5" : "border-slate-200"
                            )}>
                                <span className={cn("font-bold", theme === 'dark' ? "text-slate-500" : "text-slate-400")}>{item.label}</span>
                                <span className={cn(
                                    "font-medium flex items-center gap-1",
                                    item.trend === 'up' ? "text-emerald-500" :
                                        item.trend === 'down' ? "text-rose-500" :
                                            item.trend === 'warning' ? "text-amber-500" : (theme === 'dark' ? "text-slate-300" : "text-slate-600")
                                )}>
                                    {item.value}
                                    {item.change && <span className="opacity-70 text-[10px]">{item.change}</span>}
                                </span>
                            </div>
                        ))}
                    </div>
                    <div className="hidden md:flex items-center gap-3">
                        <Link href="/report" className={cn(
                            "flex items-center gap-2 px-3 py-1 rounded-full text-[10px] font-mono transition-colors border",
                            theme === 'dark'
                                ? "bg-white/5 hover:bg-white/10 text-slate-300 border-white/10"
                                : "bg-slate-100 hover:bg-slate-200 text-slate-600 border-slate-200"
                        )}>
                            <Terminal size={12} />
                            TERMINAL VIEW
                        </Link>

                        {/* Theme Toggle */}
                        <button
                            onClick={toggleTheme}
                            className={cn(
                                "p-1.5 rounded-full transition-colors",
                                theme === 'dark' ? "hover:bg-white/10 text-slate-400" : "hover:bg-slate-200 text-slate-500"
                            )}
                            title="Toggle Theme"
                        >
                            {theme === 'dark' ? <Sun size={14} /> : <Moon size={14} />}
                        </button>

                        {/* Logout */}
                        <button
                            onClick={handleLogout}
                            className={cn(
                                "p-1.5 rounded-full transition-colors",
                                theme === 'dark' ? "hover:bg-white/10 text-slate-400" : "hover:bg-slate-200 text-slate-500"
                            )}
                            title="Logout"
                        >
                            <LogOut size={14} />
                        </button>

                        <span className="text-[10px] font-mono text-emerald-500 animate-pulse">● LIVE</span>
                    </div>
                </div>
            </div>

            <div className="flex-1 max-w-[1600px] w-full mx-auto p-4 md:p-6 grid grid-cols-1 lg:grid-cols-12 gap-8">

                {/* LAYER 2: DAILY REGIME SUMMARY (Middle) */}
                <div className="lg:col-span-12 grid grid-cols-1 lg:grid-cols-3 gap-6">

                    {/* Left: Today's Regimes */}
                    <div className="lg:col-span-2">
                        <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-4 flex items-center gap-2">
                            <Globe size={12} /> Today's Regime Matrix
                        </h3>
                        <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
                            {regimeCards.length > 0 ? regimeCards.map((card: any, idx: number) => (
                                <div key={idx} className={cn(
                                    "border rounded-xl p-4 transition-all cursor-pointer group",
                                    theme === 'dark'
                                        ? "bg-white/5 hover:bg-white/10"
                                        : "bg-white hover:bg-slate-50 shadow-sm",
                                    card.border
                                )}>
                                    <div className="flex justify-between items-start mb-2">
                                        <span className="text-slate-400 text-xs font-bold">{card.title}</span>
                                        <Info size={12} className="text-slate-600 opacity-0 group-hover:opacity-100 transition-opacity" />
                                    </div>
                                    <div className={cn("text-lg font-bold mb-1", theme === 'dark' ? "text-white" : "text-slate-900")}>{card.status}</div>
                                    <div className={cn("text-xs font-mono", card.color)}>{card.vibe}</div>
                                </div>
                            )) : (
                                <div className="col-span-3 text-slate-500 text-sm">Waiting for Regime Analysis...</div>
                            )}
                        </div>

                        {/* Interpretation & Signals */}
                        <div className={cn(
                            "mt-6 border rounded-xl p-5",
                            theme === 'dark' ? "bg-white/5 border-white/10" : "bg-white border-slate-200 shadow-sm"
                        )}>
                            <div className="flex items-start gap-4">
                                <div className="p-2 bg-indigo-500/10 rounded-lg text-indigo-500 shrink-0">
                                    <Activity size={20} />
                                </div>
                                <div>
                                    <h4 className={cn("text-sm font-bold mb-1", theme === 'dark' ? "text-white" : "text-slate-900")}>AI Interpretation</h4>
                                    <p className={cn("text-xs leading-relaxed", theme === 'dark' ? "text-slate-400" : "text-slate-600")}>
                                        {macroData?.one_line_insight || "Analyzing market structure..."}
                                    </p>
                                    <div className="flex gap-2 mt-3 flex-wrap">
                                        {macroData?.risks?.map((risk: string, idx: number) => (
                                            <span key={idx} className="px-2 py-1 rounded bg-rose-500/10 text-rose-500 text-[10px] font-bold border border-rose-500/20">
                                                RISK: {risk}
                                            </span>
                                        ))}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Right: Historical Twin */}
                    <div className="lg:col-span-1">
                        <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-4 flex items-center gap-2">
                            <Terminal size={12} /> Historical Twin
                        </h3>
                        <div className={cn(
                            "border rounded-xl p-5 h-full relative overflow-hidden",
                            theme === 'dark' ? "bg-slate-900 border-slate-800" : "bg-slate-100 border-slate-200"
                        )}>
                            <div className="absolute top-0 right-0 p-3 opacity-10">
                                <Terminal size={100} className={theme === 'dark' ? "text-white" : "text-slate-900"} />
                            </div>
                            <div className="relative z-10">
                                <div className="text-xs text-slate-500 mb-1">MATCH DATE</div>
                                <div className="text-3xl font-bold text-amber-500 font-mono mb-4">
                                    {historian?.match_date || "Scanning..."}
                                </div>

                                <div className="space-y-4">
                                    <div>
                                        <div className="text-[10px] text-slate-500 uppercase font-bold">Context</div>
                                        <div className={cn("text-sm", theme === 'dark' ? "text-slate-300" : "text-slate-700")}>
                                            {historian?.regime_name || "Searching history..."}
                                        </div>
                                    </div>
                                    <div>
                                        <div className="text-[10px] text-slate-500 uppercase font-bold">Reasoning</div>
                                        <div className={cn("text-sm", theme === 'dark' ? "text-slate-300" : "text-slate-700")}>
                                            {historian?.human_explanation || "..."}
                                        </div>
                                    </div>
                                    <div className={cn("pt-4 border-t", theme === 'dark' ? "border-white/5" : "border-slate-300")}>
                                        <div className="flex justify-between items-center">
                                            <span className="text-xs text-slate-500">Similarity Score</span>
                                            <span className={cn("text-xl font-bold", theme === 'dark' ? "text-white" : "text-slate-900")}>
                                                {historian?.similarity_score ? `${historian.similarity_score}%` : "--"}
                                            </span>
                                        </div>
                                        <div className={cn("w-full h-1 mt-2 rounded-full overflow-hidden", theme === 'dark' ? "bg-slate-800" : "bg-slate-300")}>
                                            <div className="bg-amber-500 h-full" style={{ width: `${historian?.similarity_score || 0}%` }} />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {/* LAYER 3: LIVE INTELLIGENCE FEED (Bottom) */}
                <div className="lg:col-span-12 mt-4">
                    <div className="flex flex-col gap-4 mb-4">
                        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                            <h2 className={cn("text-sm font-bold tracking-wider flex items-center gap-2", theme === 'dark' ? "text-white" : "text-slate-900")}>
                                <Globe size={16} className="text-indigo-500" />
                                LIVE INTELLIGENCE
                            </h2>

                            <div className="flex flex-col items-start md:items-end gap-2 w-full md:w-auto">
                                <div className="flex items-center gap-4">
                                    {/* Language Toggle */}
                                    <div className={cn("flex rounded-lg p-0.5 border", theme === 'dark' ? "bg-white/5 border-white/10" : "bg-white border-slate-200")}>
                                        <button
                                            onClick={() => setSelectedLanguage('EN')}
                                            className={cn("px-2 py-0.5 text-[10px] rounded font-bold transition-all", selectedLanguage === 'EN' ? "bg-indigo-500 text-white" : "text-slate-500 hover:text-slate-300")}
                                        >
                                            EN
                                        </button>
                                        <button
                                            onClick={() => setSelectedLanguage('KO')}
                                            className={cn("px-2 py-0.5 text-[10px] rounded font-bold transition-all", selectedLanguage === 'KO' ? "bg-indigo-500 text-white" : "text-slate-500 hover:text-slate-300")}
                                        >
                                            KR
                                        </button>
                                    </div>

                                    {/* Country Filter */}
                                    <div className="flex gap-2 overflow-x-auto pb-1 scrollbar-hide w-full md:w-auto">
                                        {countries.map(country => (
                                            <button
                                                key={country}
                                                onClick={() => setSelectedCountry(country)}
                                                className={cn(
                                                    "text-[10px] px-3 py-1 rounded border transition-all whitespace-nowrap flex items-center gap-1",
                                                    selectedCountry === country
                                                        ? "bg-indigo-500/20 border-indigo-500 text-indigo-500"
                                                        : (theme === 'dark' ? "border-white/10 hover:border-white/30 text-slate-500 hover:text-slate-300" : "border-slate-200 hover:border-slate-300 text-slate-500 hover:text-slate-700")
                                                )}
                                            >
                                                <span>{getCountryFlag(country)}</span>
                                                <span>{country}</span>
                                            </button>
                                        ))}
                                        {/* Coming Soon Countries */}
                                        {comingSoonCountries.map(country => (
                                            <button
                                                key={country}
                                                disabled
                                                className={cn(
                                                    "text-[10px] px-3 py-1 rounded border whitespace-nowrap flex items-center gap-1 cursor-not-allowed opacity-50",
                                                    theme === 'dark' ? "border-white/5 bg-white/5 text-slate-600" : "border-slate-100 bg-slate-100 text-slate-400"
                                                )}
                                            >
                                                <span>{getCountryFlag(country)}</span>
                                                <span>{country}</span>
                                                <Lock size={8} className="ml-1" />
                                            </button>
                                        ))}
                                    </div>
                                </div>

                                {/* Category Filter */}
                                <div className="flex gap-2 overflow-x-auto pb-1 scrollbar-hide w-full md:w-auto">
                                    {categories.map(category => (
                                        <button
                                            key={category}
                                            onClick={() => setSelectedCategory(category)}
                                            className={cn(
                                                "text-[10px] px-3 py-1 rounded border transition-all whitespace-nowrap",
                                                selectedCategory === category
                                                    ? "bg-emerald-500/20 border-emerald-500 text-emerald-500"
                                                    : (theme === 'dark' ? "border-white/10 hover:border-white/30 text-slate-500 hover:text-slate-300" : "border-slate-200 hover:border-slate-300 text-slate-500 hover:text-slate-700")
                                            )}
                                        >
                                            {category}
                                        </button>
                                    ))}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className={cn(
                    "border rounded-xl overflow-hidden min-h-[400px]",
                    theme === 'dark' ? "bg-[#0a0a0a] border-white/10" : "bg-white border-slate-200 shadow-sm"
                )}>
                    {loading ? (
                        <div className="flex flex-col items-center justify-center h-[400px] text-slate-500 gap-3">
                            <div className="w-6 h-6 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin" />
                            <span className="text-xs font-mono animate-pulse">ESTABLISHING SECURE UPLINK...</span>
                        </div>
                    ) : news.length === 0 ? (
                        <div className="flex flex-col items-center justify-center h-[400px] text-slate-500">
                            <Info size={24} className="mb-2 opacity-50" />
                            <span className="text-xs font-mono">NO INTELLIGENCE FOUND FOR {selectedCountry}</span>
                        </div>
                    ) : (
                        <div className={cn("divide-y", theme === 'dark' ? "divide-white/5" : "divide-slate-100")}>
                            {news.map((item, idx) => (
                                <a
                                    key={idx}
                                    href={item.url || "#"}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className={cn(
                                        "flex items-start gap-3 md:gap-4 p-3 md:p-4 transition-colors group",
                                        theme === 'dark' ? "hover:bg-white/5" : "hover:bg-slate-50"
                                    )}
                                >
                                    <div className="shrink-0 w-20 md:w-28 text-center pt-1 flex flex-col items-center gap-1.5">
                                        {/* Top: Category Badge */}
                                        <span className={cn(
                                            "text-[9px] md:text-[10px] font-bold px-1.5 md:px-2 py-0.5 rounded border w-full text-center truncate",
                                            item.category === 'ECONOMY' ? "text-emerald-500 border-emerald-500/30 bg-emerald-500/10" :
                                                item.category === 'FINANCE' ? "text-blue-500 border-blue-500/30 bg-blue-500/10" :
                                                    item.category === 'CRYPTO' ? "text-amber-500 border-amber-500/30 bg-amber-500/10" :
                                                        item.category === 'POLITICS' ? "text-rose-500 border-rose-500/30 bg-rose-500/10" :
                                                            "text-slate-400 border-slate-500/30 bg-slate-500/10"
                                        )}>
                                            {item.category || "GEN"}
                                        </span>

                                        {/* Bottom: Flag + Score */}
                                        <div className="flex items-center justify-center gap-2">
                                            <span className="text-base md:text-lg leading-none" title={item.country || "Global"}>
                                                {getCountryFlag(item.country || 'ALL')}
                                            </span>
                                            {item.importance_score && item.importance_score > 0 ? (
                                                <span className="text-xs font-bold font-mono text-slate-400">
                                                    {item.importance_score}
                                                </span>
                                            ) : (
                                                <span className="text-[9px] font-mono text-slate-600 animate-pulse">
                                                    ...
                                                </span>
                                            )}
                                        </div>
                                    </div>
                                    <div className="flex-1 min-w-0">
                                        <h4 className={cn(
                                            "text-sm font-medium transition-colors font-mono leading-tight mb-1",
                                            theme === 'dark' ? "text-slate-200 group-hover:text-indigo-300" : "text-slate-800 group-hover:text-indigo-600"
                                        )}>
                                            {/* Use selectedLanguage for translation */}
                                            {(selectedLanguage === 'KO') ? (item.clean_title || item.title) : item.title}
                                        </h4>
                                    </div>
                                    <div className="shrink-0 text-right pt-1 hidden sm:block">
                                        <span className="text-[10px] text-slate-600 font-mono block">
                                            {new Date(item.published_at).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: false, timeZone: 'America/New_York' })} EST
                                        </span>
                                        <span className="text-[10px] text-indigo-400 font-mono block">
                                            {new Date(item.published_at).toLocaleTimeString('ko-KR', { hour: '2-digit', minute: '2-digit', hour12: false, timeZone: 'Asia/Seoul' })} KST
                                        </span>
                                    </div>
                                    <ArrowUpRight size={14} className="text-slate-700 group-hover:text-indigo-400 transition-colors opacity-0 group-hover:opacity-100 mt-1" />
                                </a>
                            ))}
                        </div>
                    )}
                </div>
            </div>

        </div >
    )
}

export default function Dashboard() {
    return (
        <Suspense fallback={<div className="min-h-screen bg-[#050505] flex items-center justify-center text-slate-500">Loading...</div>}>
            <DashboardContent />
        </Suspense>
    )
}
