"use client"

import { useState, useEffect, Suspense } from "react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { useSearchParams } from "next/navigation"
import {
    Activity, ChevronDown, CloudLightning, DollarSign, Globe, Info, Lock, LogOut, Moon, Sun, Terminal, Unlock
} from "lucide-react"
import { cn } from "../../lib/utils"
import { supabase } from "../../lib/supabase"
import { DASHBOARD_CONFIG, getCountryFlag } from "../../lib/config"
import { NewsCard, NewsItem } from "../../components/dashboard/NewsCard"
import { RegimeCard } from "../../components/dashboard/RegimeCard"
import { MacroIndicator } from "../../components/dashboard/MacroIndicator"
import { MarketBoard } from "../../components/dashboard/MarketBoard"

function DashboardContent() {
    const router = useRouter()
    const searchParams = useSearchParams()
    const initialCountry = searchParams.get('country') || 'ALL'

    const [selectedCountry, setSelectedCountry] = useState<string>(initialCountry)
    const [selectedCategory, setSelectedCategory] = useState<string>('ALL')
    const [selectedLanguage, setSelectedLanguage] = useState<string>('EN') // EN, KO
    const [news, setNews] = useState<NewsItem[]>([])
    const [loading, setLoading] = useState(true)
    const [macroData, setMacroData] = useState<any>(null)
    const [theme, setTheme] = useState<'dark' | 'light'>('dark')
    const [isCountryDropdownOpen, setIsCountryDropdownOpen] = useState(false)

    // Fetch Macro Data (Generated by GitHub Action)
    useEffect(() => {
        async function fetchMacroData() {
            try {
                const res = await fetch('/dashboard_data.json?t=' + new Date().getTime()) // Cache bust
                if (res.ok) {
                    const data = await res.json()
                    console.log("Macro Data Loaded:", data)
                    setMacroData(data)
                } else {
                    console.error("Failed to load macro data")
                }
            } catch (e) {
                console.error("Error loading macro data:", e)
            }
        }
        fetchMacroData()
    }, [])

    useEffect(() => {
        async function fetchData() {
            setLoading(true)
            console.log(`Fetching news for Country: ${selectedCountry}, Category: ${selectedCategory}`)

            const scanDate = new Date()
            scanDate.setDate(scanDate.getDate() - DASHBOARD_CONFIG.scanRangeDays)

            let query = supabase
                .from('ingest_news')
                .select('id, title, clean_title, published_at, summary, url, source, country, category, importance_score, title_ko, summary_ko')

            // 1. Apply Filters FIRST
            query = query.gte('importance_score', DASHBOARD_CONFIG.minImportanceScore)
                .gte('published_at', scanDate.toISOString())

            if (selectedCountry !== 'ALL') {
                if (selectedCountry === 'CRYPTO') {
                    query = query.textSearch('title', "'bitcoin' | 'crypto' | 'btc' | 'eth'")
                } else {
                    query = query.eq('country', selectedCountry)
                }
            }

            if (selectedCategory !== 'ALL') {
                query = query.eq('category', selectedCategory)
            }

            // 2. Apply Sort & Limit LAST
            query = query.order('published_at', { ascending: false })
                .limit(50)

            const { data, error } = await query

            if (error) {
                console.error("Error fetching news:", error)
            }

            if (data) {
                console.log(`Fetched ${data.length} items`)
                setNews(data)
            }
            setLoading(false)
        }
        fetchData()

        // Real-time subscription
        const channel = supabase
            .channel('public:ingest_news')
            .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'ingest_news' }, (payload) => {
                console.log('New news:', payload)
                // In a real app, we'd prepend this to the list
            })
            .subscribe()

        return () => {
            supabase.removeChannel(channel)
        }
    }, [selectedCountry, selectedCategory])

    // Parse Macro Data or Use Fallback
    const historian = macroData?.historian_insight || null

    // Macro Indicators
    const macroIndicators = [
        { label: "RATES", value: macroData?.factor_interpretation?.rates || "Analyzing...", trend: "neutral", change: undefined },
        { label: "DOLLAR", value: macroData?.factor_interpretation?.dollar || "Analyzing...", trend: "neutral", change: undefined },
        { label: "RISK", value: macroData?.factor_interpretation?.risk || "Analyzing...", trend: "neutral", change: undefined },
        { label: "LIQUIDITY", value: macroData?.factor_interpretation?.liquidity || "Stable", trend: "neutral", change: undefined },
    ]

    // Regime Cards
    const regimeCards = macroData?.actions ? macroData.actions.map((action: any) => ({
        title: action.asset,
        status: action.type.toUpperCase(),
        vibe: action.label,
        color: action.type === 'buy' ? "text-emerald-400" : action.type === 'reduce' ? "text-rose-400" : "text-slate-400",
        border: action.type === 'buy' ? "border-emerald-500/30" : action.type === 'reduce' ? "border-rose-500/30" : "border-slate-500/30"
    })) : []

    const handleLogout = () => {
        router.push('/')
    }

    const toggleTheme = () => {
        setTheme(prev => prev === 'dark' ? 'light' : 'dark')
    }

    const handleRefresh = () => {
        window.location.reload()
    }

    return (
        <div className={cn(
            "min-h-screen font-sans selection:bg-indigo-500/30 flex flex-col transition-colors duration-300",
            theme === 'dark' ? "bg-[#050505] text-slate-200" : "bg-slate-50 text-slate-900"
        )}>

            {/* LAYER 1: MACRO NOW BAR (Sticky Top) */}
            <div className={cn(
                "sticky top-0 z-50 backdrop-blur-md border-b shadow-lg transition-colors duration-300",
                theme === 'dark' ? "bg-[#0a0a0a]/95 border-white/5" : "bg-white/95 border-slate-200"
            )}>
                <div className="max-w-7xl mx-auto px-4 h-12 flex items-center justify-between overflow-x-auto no-scrollbar">
                    <div className="flex items-center gap-6 text-xs font-mono whitespace-nowrap">
                        <button
                            onClick={handleRefresh}
                            className="flex items-center gap-2 text-indigo-500 font-bold mr-4 hover:opacity-80 transition-opacity"
                            title="Refresh Dashboard"
                        >
                            <Activity size={14} />
                            <span>MACRO NOW</span>
                        </button>
                        {macroIndicators.map((item, idx) => (
                            <MacroIndicator
                                key={idx}
                                label={item.label}
                                value={item.value}
                                trend={item.trend as any}
                                change={item.change}
                                theme={theme}
                            />
                        ))}
                    </div>
                    <div className="hidden md:flex items-center gap-3">
                        <Link href="/report" className={cn(
                            "flex items-center gap-2 px-3 py-1 rounded-full text-[10px] font-mono transition-colors border",
                            theme === 'dark'
                                ? "bg-white/5 hover:bg-white/10 text-slate-300 border-white/10"
                                : "bg-slate-100 hover:bg-slate-200 text-slate-600 border-slate-200"
                        )}>
                            <Terminal size={12} />
                            TERMINAL VIEW
                        </Link>

                        {/* Theme Toggle */}
                        <button
                            onClick={toggleTheme}
                            className={cn(
                                "p-1.5 rounded-full transition-colors",
                                theme === 'dark' ? "hover:bg-white/10 text-slate-400" : "hover:bg-slate-200 text-slate-500"
                            )}
                            title="Toggle Theme"
                        >
                            {theme === 'dark' ? <Sun size={14} /> : <Moon size={14} />}
                        </button>

                        {/* Logout */}
                        <button
                            onClick={handleLogout}
                            className={cn(
                                "p-1.5 rounded-full transition-colors",
                                theme === 'dark' ? "hover:bg-white/10 text-slate-400" : "hover:bg-slate-200 text-slate-500"
                            )}
                            title="Logout"
                        >
                            <LogOut size={14} />
                        </button>

                        <span className="text-[10px] font-mono text-emerald-500 animate-pulse">● LIVE</span>
                    </div>
                </div>
            </div>

            {/* LAYER 1.5: MARKET BOARD */}
            <MarketBoard data={macroData?.market_snapshot} theme={theme} />

            <div className="flex-1 max-w-7xl w-full mx-auto p-4 md:p-6 grid grid-cols-1 lg:grid-cols-12 gap-8">

                {/* LAYER 2: DAILY REGIME SUMMARY (Middle) */}
                <div className="lg:col-span-12 grid grid-cols-1 lg:grid-cols-3 gap-6">

                    {/* Left: Today's Regimes */}
                    <div className="lg:col-span-2">
                        <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-4 flex items-center gap-2">
                            <Globe size={12} /> Today's Regime Matrix
                        </h3>
                        <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
                            {regimeCards.length > 0 ? regimeCards.map((card: any, idx: number) => (
                                <RegimeCard
                                    key={idx}
                                    title={card.title}
                                    status={card.status}
                                    vibe={card.vibe}
                                    color={card.color}
                                    border={card.border}
                                    theme={theme}
                                />
                            )) : (
                                <div className="col-span-3 text-slate-500 text-sm">Waiting for Regime Analysis...</div>
                            )}
                        </div>

                        {/* Interpretation & Signals */}
                        <div className={cn(
                            "mt-6 border rounded-xl p-5",
                            theme === 'dark' ? "bg-white/5 border-white/10" : "bg-white border-slate-200 shadow-sm"
                        )}>
                            <div className="flex items-start gap-4">
                                <div className="p-2 bg-indigo-500/10 rounded-lg text-indigo-500 shrink-0">
                                    <Activity size={20} />
                                </div>
                                <div>
                                    <h4 className={cn("text-sm font-bold mb-1", theme === 'dark' ? "text-white" : "text-slate-900")}>AI Interpretation</h4>
                                    <p className={cn("text-xs leading-relaxed", theme === 'dark' ? "text-slate-400" : "text-slate-600")}>
                                        {macroData?.one_line_insight || "Analyzing market structure..."}
                                    </p>
                                    <div className="flex gap-2 mt-3 flex-wrap">
                                        {macroData?.risks?.map((risk: string, idx: number) => (
                                            <span key={idx} className="px-2 py-1 rounded bg-rose-500/10 text-rose-500 text-[10px] font-bold border border-rose-500/20">
                                                RISK: {risk}
                                            </span>
                                        ))}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Right: Historical Twin */}
                    <div className="lg:col-span-1">
                        <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-4 flex items-center gap-2">
                            <Terminal size={12} /> Historical Twin
                        </h3>
                        <div className={cn(
                            "border rounded-xl p-5 h-full relative overflow-hidden",
                            theme === 'dark' ? "bg-slate-900 border-slate-800" : "bg-slate-100 border-slate-200"
                        )}>
                            <div className="absolute top-0 right-0 p-3 opacity-10">
                                <Terminal size={100} className={theme === 'dark' ? "text-white" : "text-slate-900"} />
                            </div>
                            <div className="relative z-10">
                                <div className="text-xs text-slate-500 mb-1">MATCH DATE</div>
                                <div className="text-3xl font-bold text-amber-500 font-mono mb-4">
                                    {historian?.match_date || "Scanning..."}
                                </div>

                                <div className="space-y-4">
                                    <div>
                                        <div className="text-[10px] text-slate-500 uppercase font-bold">Context</div>
                                        <div className={cn("text-sm", theme === 'dark' ? "text-slate-300" : "text-slate-700")}>
                                            {historian?.regime_name || "Searching history..."}
                                        </div>
                                    </div>
                                    <div>
                                        <div className="text-[10px] text-slate-500 uppercase font-bold">Reasoning</div>
                                        <div className={cn("text-sm", theme === 'dark' ? "text-slate-300" : "text-slate-700")}>
                                            {historian?.human_explanation || "..."}
                                        </div>
                                    </div>
                                    <div className={cn("pt-4 border-t", theme === 'dark' ? "border-white/5" : "border-slate-300")}>
                                        <div className="flex justify-between items-center">
                                            <span className="text-xs text-slate-500">Similarity Score</span>
                                            <span className={cn("text-xl font-bold", theme === 'dark' ? "text-white" : "text-slate-900")}>
                                                {historian?.similarity_score ? `${historian.similarity_score}%` : "--"}
                                            </span>
                                        </div>
                                        <div className={cn("w-full h-1 mt-2 rounded-full overflow-hidden", theme === 'dark' ? "bg-slate-800" : "bg-slate-300")}>
                                            <div className="bg-amber-500 h-full" style={{ width: `${historian?.similarity_score || 0}%` }} />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {/* LAYER 3: LIVE INTELLIGENCE FEED (Bottom) */}
                <div className="lg:col-span-12 mt-4">
                    <div className="flex flex-col gap-4 mb-4">
                        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                            <h2 className={cn("text-sm font-bold tracking-wider flex items-center gap-2", theme === 'dark' ? "text-white" : "text-slate-900")}>
                                <Globe size={16} className="text-indigo-500" />
                                LIVE INTELLIGENCE
                            </h2>

                            <div className="flex flex-col items-start md:items-end gap-2 w-full md:w-auto">
                                <div className="flex items-center gap-4">
                                    {/* Language Toggle */}
                                    <div className={cn("flex rounded-lg p-0.5 border", theme === 'dark' ? "bg-white/5 border-white/10" : "bg-white border-slate-200")}>
                                        <button
                                            onClick={() => setSelectedLanguage('EN')}
                                            className={cn("px-2 py-0.5 text-[10px] rounded font-bold transition-all", selectedLanguage === 'EN' ? "bg-indigo-500 text-white" : "text-slate-500 hover:text-slate-300")}
                                        >
                                            EN
                                        </button>
                                        <button
                                            onClick={() => setSelectedLanguage('KO')}
                                            className={cn("px-2 py-0.5 text-[10px] rounded font-bold transition-all", selectedLanguage === 'KO' ? "bg-indigo-500 text-white" : "text-slate-500 hover:text-slate-300")}
                                        >
                                            KR
                                        </button>
                                    </div>

                                    {/* Country Dropdown */}
                                    <div className="relative z-20">
                                        <button
                                            onClick={() => setIsCountryDropdownOpen(!isCountryDropdownOpen)}
                                            className={cn(
                                                "flex items-center gap-2 px-3 py-1.5 rounded-lg border transition-all min-w-[100px] justify-between",
                                                theme === 'dark'
                                                    ? "bg-white/5 border-white/10 hover:bg-white/10 text-slate-200"
                                                    : "bg-white border-slate-200 hover:bg-slate-50 text-slate-700"
                                            )}
                                        >
                                            <div className="flex items-center gap-2">
                                                <span>{getCountryFlag(selectedCountry)}</span>
                                                <span className="text-xs font-bold">{selectedCountry}</span>
                                            </div>
                                            <ChevronDown size={14} className={cn("transition-transform", isCountryDropdownOpen ? "rotate-180" : "")} />
                                        </button>

                                        {isCountryDropdownOpen && (
                                            <div className={cn(
                                                "absolute top-full left-0 mt-2 w-40 rounded-xl border shadow-xl overflow-hidden p-1 backdrop-blur-xl",
                                                theme === 'dark'
                                                    ? "bg-[#0a0a0a]/95 border-white/10"
                                                    : "bg-white/95 border-slate-200"
                                            )}>
                                                <div className="space-y-0.5">
                                                    {DASHBOARD_CONFIG.countries.map(country => (
                                                        <button
                                                            key={country}
                                                            onClick={() => {
                                                                setSelectedCountry(country)
                                                                setIsCountryDropdownOpen(false)
                                                            }}
                                                            className={cn(
                                                                "w-full text-left px-3 py-2 rounded-lg text-xs font-bold flex items-center gap-2 transition-colors",
                                                                selectedCountry === country
                                                                    ? "bg-indigo-500 text-white"
                                                                    : (theme === 'dark' ? "hover:bg-white/10 text-slate-400 hover:text-slate-200" : "hover:bg-slate-100 text-slate-600 hover:text-slate-900")
                                                            )}
                                                        >
                                                            <span>{getCountryFlag(country)}</span>
                                                            <span>{country}</span>
                                                        </button>
                                                    ))}
                                                    <div className={cn("my-1 border-t", theme === 'dark' ? "border-white/5" : "border-slate-100")} />
                                                    {DASHBOARD_CONFIG.comingSoonCountries.map(country => (
                                                        <button
                                                            key={country}
                                                            disabled
                                                            className={cn(
                                                                "w-full text-left px-3 py-2 rounded-lg text-xs font-bold flex items-center justify-between opacity-50 cursor-not-allowed",
                                                                theme === 'dark' ? "text-slate-600" : "text-slate-400"
                                                            )}
                                                        >
                                                            <div className="flex items-center gap-2">
                                                                <span>{getCountryFlag(country)}</span>
                                                                <span>{country}</span>
                                                            </div>
                                                            <Lock size={10} />
                                                        </button>
                                                    ))}
                                                </div>
                                            </div>
                                        )}
                                    </div>
                                </div>

                                {/* Category Filter */}
                                <div className="flex gap-2 overflow-x-auto pb-1 scrollbar-hide w-full md:w-auto">
                                    {DASHBOARD_CONFIG.categories.map(category => (
                                        <button
                                            key={category}
                                            onClick={() => setSelectedCategory(category)}
                                            className={cn(
                                                "text-[10px] px-3 py-1 rounded border transition-all whitespace-nowrap",
                                                selectedCategory === category
                                                    ? "bg-emerald-500/20 border-emerald-500 text-emerald-500"
                                                    : (theme === 'dark' ? "border-white/10 hover:border-white/30 text-slate-500 hover:text-slate-300" : "border-slate-200 hover:border-slate-300 text-slate-500 hover:text-slate-700")
                                            )}
                                        >
                                            {category}
                                        </button>
                                    ))}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className={cn(
                        "lg:col-span-12 border rounded-xl overflow-hidden min-h-[400px]",
                        theme === 'dark' ? "bg-[#0a0a0a] border-white/10" : "bg-white border-slate-200 shadow-sm"
                    )}>
                        {loading ? (
                            <div className="flex flex-col items-center justify-center h-[400px] text-slate-500 gap-3">
                                <div className="w-6 h-6 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin" />
                                <span className="text-xs font-mono animate-pulse">ESTABLISHING SECURE UPLINK...</span>
                            </div>
                        ) : news.length === 0 ? (
                            <div className="flex flex-col items-center justify-center h-[400px] text-slate-500">
                                <Info size={24} className="mb-2 opacity-50" />
                                <span className="text-xs font-mono">NO INTELLIGENCE FOUND FOR {selectedCountry}</span>
                            </div>
                        ) : (
                            <div className={cn("divide-y", theme === 'dark' ? "divide-white/5" : "divide-slate-100")}>
                                {news.map((item, idx) => (
                                    <NewsCard
                                        key={idx}
                                        item={item}
                                        theme={theme}
                                        selectedLanguage={selectedLanguage}
                                    />
                                ))}
                            </div>
                        )}
                    </div>
                </div>

            </div>

        </div >
    )
}

export default function Dashboard() {
    return (
        <Suspense fallback={<div className="min-h-screen bg-[#050505] flex items-center justify-center text-slate-500">Loading...</div>}>
            <DashboardContent />
        </Suspense>
    )
}
