-- 1. Archive Existing Table
ALTER TABLE IF EXISTS ingest_news RENAME TO news_archive_legacy;

-- 2. Create News Raw (Landing Zone)
CREATE TABLE IF NOT EXISTS news_raw (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT NOT NULL,
    title TEXT,
    country TEXT,
    source TEXT,
    published_at TIMESTAMP WITH TIME ZONE,
    fetched_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    raw_data JSONB,
    processed BOOLEAN DEFAULT FALSE,
    UNIQUE(url)
);

-- 3. Create New Ingest News (Golden Data)
-- Schema inferred from usage: id, title, clean_title, summary, url, published_at, country, source, category, importance_score, is_refined, summary_status
CREATE TABLE IF NOT EXISTS ingest_news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Core Content
    title TEXT NOT NULL,
    clean_title TEXT,
    summary TEXT,
    url TEXT NOT NULL,
    
    -- Metadata
    published_at TIMESTAMP WITH TIME ZONE,
    country TEXT, -- 'US', 'KR', 'JP', 'CN'
    source TEXT,
    category TEXT, -- 'ECONOMY', 'BUSINESS', etc.
    ticker TEXT,
    
    -- Refinement Status
    importance_score INTEGER DEFAULT 0,
    is_refined BOOLEAN DEFAULT FALSE,
    
    -- Worker Status
    summary_status TEXT DEFAULT 'PENDING', -- 'PENDING', 'DONE', 'FAILED', 'SKIPPED'
    
    UNIQUE(url)
);

-- 4. Enable RLS & Policies
ALTER TABLE news_raw ENABLE ROW LEVEL SECURITY;
ALTER TABLE ingest_news ENABLE ROW LEVEL SECURITY;

-- Allow Service Role Full Access (for scripts)
CREATE POLICY "Service Role Full Access Raw" ON news_raw USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access Ingest" ON ingest_news USING (true) WITH CHECK (true);

-- Allow Public Read (for Dashboard)
CREATE POLICY "Public Read Ingest" ON ingest_news FOR SELECT USING (true);
