-- Create news_raw table
CREATE TABLE IF NOT EXISTS news_raw (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT NOT NULL,
    title TEXT,
    country TEXT,
    source TEXT,
    published_at TIMESTAMP WITH TIME ZONE,
    fetched_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    raw_data JSONB,
    processed BOOLEAN DEFAULT FALSE,
    UNIQUE(url)
);

-- Enable RLS
ALTER TABLE news_raw ENABLE ROW LEVEL SECURITY;

-- Allow public read access (if needed, or restrict to service role)
CREATE POLICY "Service Role Full Access News Raw" ON news_raw USING (true) WITH CHECK (true);
